version: '3.9'

services:
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '$POSTGRES_PORT:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:5.0
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '$PGADMIN_PORT:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  influxdb:    
    image: influxdb:2.0
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '$INFLUXDB_PORT:8086'
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - influxdb2_config:/etc/influxdb2

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    env_file:
      - '.env'
    user: "0"
    links:
      - influxdb
    volumes:
#      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana:/etc/grafana/provisioning/datasources
      - grafana:/var/lib/grafana
    ports: 
      - '$GRAFANA_PORT:3000'

#  chronograf: # Some influxdb controllers
#    image: chronograf:latest
##    environment:
##      - BASE_PATH=/chronograf
#    restart: unless-stopped
#    volumes:
#      - chronograf-storage:/var/lib/chronograf
#    ports:
#      - '$CHRONOGRAF_PORT:8888'
#    depends_on:
#      - influxdb
#    env_file:
#      - '.env'

#  app:
#    build: app/
#    restart: unless-stopped
#    env_file:
#      - '.env'
#    depends_on:
#    - influxdb
#    - postgres

#  nginx:
#    build: nginx/
#    env_file:
#      - '.env'
#    ports: 
#      - '80:80'
#    restart: unless-stopped
#    volumes:
#      - ./nginx/content:/var/www/html
#      - ./nginx/sites/:/etc/nginx/conf.d
    
#    depends_on:
#    - app

volumes:
  postgres:
    driver: local
    name: postgres
  
  pgadmin:
    driver: local
    name: pgadmin

  influxdb2_data:
    driver: local
    name: influxdb2_data

  influxdb2_config:
    driver: local
    name: influxdb2_config
  
  chronograf-storage:
    driver: local
    name: chronograf-storage
  
  grafana:
    driver: local
    name: grafana
