version: '3.8'
services:

  postgres:
    image: 'postgres'
    env_file:
      - '.env'
    ports:
      - '$POSTGRES_PORT:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      backend_dev:
        aliases:
          - postgres

  pgadmin:
    image: dpage/pgadmin4    
    env_file:
      - '.env'
    ports:
      - '$PGADMIN_PORT:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      backend_dev:
        aliases:
          - pgadmin

networks:
  backend_dev:
    driver: bridge
  
volumes:
  postgres:
    driver: local
    name: postgres
  
  pgadmin:
    driver: local
    name: pgadmin