version: '3.8'

services:

  influxdb: # An optimized Database for time series. 
            # https://www.influxdata.com/
    
    image: influxdb:latest # quay.io/influxdb/influxdb:v2.0.2
    # command: influxdb --reporting-disabled
    env_file:
      - '.env'
    volumes:
      # Mount for influxdb data directory
      - influxdb-data:/var/lib/influxdb
      # Mount for influxdb configuration
      - influxdb-config:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
    # - "8082:8082"

  chronograf: # Some influxdb controllers
    image: chronograf:latest
    ports:
      - "38888:8888"
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    env_file:
      - '.env'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - '.env'
    user: "0"
    links:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana

  #app:
  #  build: .app/
    
  #  env_file:
  #    - '.env'
    
  #  depends_on:
  #    - influxdb


volumes:
  influxdb-data:
    driver: local
    name: influxdb-data
  
  influxdb-config:
    driver: local
    name: influxdb-config
  
  chronograf-storage:
    driver: local
    name: chronograf-storage

  grafana-data:
    driver: local
    name: grafana-data