version: '3.9'

services:
  postgres:
    image: 'postgres'
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '$POSTGRES_PORT:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '$PGADMIN_PORT:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  influxdb:    
    image: influxdb:latest # 1.8 version. For the 2.x version: 
                           # quay.io/influxdb/influxdb:v2.0.2
    # command: influxdb --reporting-disabled
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '$INFLUXDB_PORT:8086' 
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-config:/etc/influxdb/

  chronograf: # Some influxdb controllers
    image: chronograf:latest
    environment:
    - BASE_PATH=/chronograf
    restart: unless-stopped
    volumes:
      - chronograf-storage:/var/lib/chronograf
    ports:
      - '$CHRONOGRAF_PORT:8888'
    depends_on:
      - influxdb
    env_file:
      - '.env'

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    env_file:
      - '.env'
    user: "0"
    links:
      - influxdb
    volumes:
      - ./src/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./src/grafana:/etc/grafana/provisioning/datasources
      - ./src/grafana:/var/lib/grafana
    ports: 
      - '$GRAFANA_PORT:3000'

#  app:
#    build: app/
#    restart: unless-stopped
#    env_file:
#      - '.env'
#    depends_on:
#    - influxdb

  nginx:
    build: ./src/nginx/
    env_file:
      - '.env'
    ports: 
      - '80:80'
    restart: unless-stopped
    volumes:
      - ./src/content:/var/www/html
      - ./src/nginx/sites/:/etc/nginx/conf.d
    
    depends_on:
    - influxdb
    - grafana
    - chronograf
#    - app

volumes:
  postgres:
    driver: local
    name: postgres
  
  pgadmin:
    driver: local
    name: pgadmin

  influxdb-data:
    driver: local
    name: influxdb-data
  
  influxdb-config:
    driver: local
    name: influxdb-config
  
  chronograf-storage:
    driver: local
    name: chronograf-storage