version: '3.9'

services:
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '$POSTGRES_PORT:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:5.0
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '$PGADMIN_PORT:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  influxdb:    
    image: influxdb:2.0
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '$INFLUXDB_PORT:8086'
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - influxdb2_config:/etc/influxdb2

#  app:
#    build: app/
#    restart: unless-stopped
#    env_file:
#      - '.env'
#    depends_on:
#    - influxdb
#    - postgres

#  nginx:
#    build: nginx/
#    env_file:
#      - '.env'
#    ports: 
#      - '80:80'
#    restart: unless-stopped
#    volumes:
#      - ./nginx/content:/var/www/html
#      - ./nginx/sites/:/etc/nginx/conf.d
    
#    depends_on:
#    - app

volumes:
  postgres:
    driver: local
    name: postgres
  
  pgadmin:
    driver: local
    name: pgadmin

  influxdb2_data:
    driver: local
    name: influxdb2_data

  influxdb2_config:
    driver: local
    name: influxdb2_config
